62	İSTANBUL	İSTANBUL İL SAĞLIK MÜDÜRLÜĞÜ 1 NOLU HALK SAĞLIĞI LABORATUVARI
63	İSTANBUL	İSTANBUL BAKIRKÖY DR. SADİ KONUK EĞİTİM ARAŞTIRMA HASTANESİ MOLEKÜLER MİKROBİYOLOJİ LABORATUVARI
65	İSTANBUL	İSTANBUL SBÜ HAMİDİYE ŞİŞLİ ETFAL EĞİTİM VE ARAŞTIRMA HASTANESİ (bayramda da açıkmış) adam güvenilir değil hiç
66	İSTANBUL	SULTANGAZİ HASEKİ EĞİTİM ARAŞTIRMA HASTANESİ
68	İSTANBUL	İSTANBUL ÜNİVERSİTESİ İSTANBUL TIP FAKÜLTESİ VİROLOJİ VE TEMEL İMMİNOLOJİ BİLİM DALI (buraya giderim bayramda açık dedi acilden randevusuz)
71	İSTANBUL	BEZMİALEM VAKIF ÜNİVERSİTESİ ÜNİVERSİTESİ TIP FAKÜLTESİ TIBBİ MİKROBİYOLOJİ LABORATUVARI
72	İSTANBUL	ŞİŞLİ FLORENCE NIGHTINGALE HASTANESİ ENFEKSİYON HASTALIKLARI VE KLİNİK MİKROBİYOLOJL AD.
73	İSTANBUL	İSTANBUL ÜNİVERSİTESİ-CERRAHPAŞA CERRAHPAŞA TIP FAKÜLTESİ TIBBİ MİKROBİYOLOJİ AD.
74	İSTANBUL	BİRUNİ ÜNİVERSİTES HASTANESİ MERKEZ LABORATUVARI
76	İSTANBUL	PROF.DR.CEMİL TAŞCIOĞLU ŞEHİR HASTANESİ (TUSEB)
78	İSTANBUL	ADLİ TIP KURUMU BAŞKANLIĞI MORG İHTİSAS DAİRESİ – MİKROBİYOLOJİ LABORATUVARI
80	İSTANBUL	İSTİNYE ÜNİVERSİTESİ GENETİK HASTALIKLAR DEĞERLENDİRME MERKEZİ
84	İSTANBUL	KOÇ ÜNİVERSİTESİ HASTANESİ MOLEKÜLER MİKROBİYOLOJİ LABORATUVARI